import Head from 'next/head'
import Link from "next/link";
import {Auth, ThemeSupa} from '@supabase/auth-ui-react'
import {useSession} from '@supabase/auth-helpers-react'

import {GameList} from "../components/game_list";
import {supabase} from "../chess/supabase";

export default function Home() {
	const session = useSession();

	// function that adds a row to the table "games" on supabase
	async function create_game() {
		let {error} = await supabase.from('games').insert([
			{
				board: [{hi: "hi"}, {lol: "hi2"}],
				created_at: new Date().toISOString(),
			}
		]);
		if (error) {
			throw error;
		}
	}

	return (
		<>
			<Head>
				<title>chess test</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Link href="/game">view board</Link>
			<Link href="/profile">profile test</Link>
			<GameList/>
			<div className="container" style={{padding: '50px 0 100px 0'}}>
				{!session ? (
					<Auth supabaseClient={supabase} appearance={{theme: ThemeSupa}} providers={["google"]} theme="dark"/>
				) : (
					<>
						<button onClick={() => {
							create_game().then(_ => alert('Game created!'));
						}}>create game test
						</button>
						<p>signed in</p>
						<button className="button block" onClick={() => supabase.auth.signOut()}>
							Sign Out
						</button>
					</>

				)}
			</div>
			<a href={"https://github.com/Jeffmagma/chess"}>source code</a>
		</>
	)
}
