import Head from 'next/head'
import {motion} from 'framer-motion'
import React, {MutableRefObject, useRef, useState} from "react";

function DragThing() {
    const [top, settop] = useState(100);
    const [left, setleft] = useState(100);
    const xd = useRef<HTMLDivElement>(null) as MutableRefObject<HTMLDivElement>;
    return (<motion.div ref={xd} drag style={{border: "1px solid green", position: "fixed", top: top + "px", left: left + "px"}} dragSnapToOrigin={true} dragElastic={0} dragMomentum={false} onDragEnd={(event: PointerEvent) => {
        const x = document.elementsFromPoint(event.clientX, event.clientY)[1].getBoundingClientRect();
        console.log(x.top, x.left);
        settop(x.top + 40);
        setleft(x.left + 20);
    }
    }>piece
    </motion.div>);
}

function Square({row, col}: { row: number, col: number }) {
    return <div style={{width: "100px", height: "100px", border: "1px cyan solid", position: "absolute", top: col * 100, left: row * 100}}>
        {String.fromCharCode('A'.charCodeAt(0) + row) + (col + 1)}
    </div>
}

function Board() {
    return (<div style={{position: "absolute"}}>
        {[...Array(8)].map((element, row) =>
            [...Array(8)].map((element, col) => {
                return <Square key={"" + row + col} row={row} col={col}/>
            })
        )}
        <DragThing/>
    </div>)
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Board/>
        </>
    )
}
